-- 0013_quartz_cluster_tables.sql
-- Step 12: the standard Quartz.NET SQL Server AdoJobStore tables (QRTZ_*), used in CLUSTERED mode.
--
-- These are the cluster bookkeeping tables that make a scheduled trigger fire on EXACTLY ONE worker
-- replica even when several replicas point at this same database: QRTZ_LOCKS gives Quartz the row
-- locks it uses to serialize scheduler instances, QRTZ_SCHEDULER_STATE tracks the live instances and
-- their check-in, and QRTZ_FIRED_TRIGGERS records the in-flight fire of each trigger so exactly one
-- node acquires it. Without these the worker cannot be clustered (the design's "single-fire under
-- clustering" requirement).
--
-- Schema source: the canonical Quartz.NET `tables_sqlServer.sql` for table prefix QRTZ_ (the default),
-- adapted to be IDEMPOTENT (each object guarded by IF NOT EXISTS) so it applies cleanly atop 0000-0012
-- and a re-run is a no-op (DbUp also journals it once). The price-median table is NOT here — it is
-- created in Step 7's 0010 and only POPULATED by the Step 12 nightly job.

IF OBJECT_ID(N'dbo.QRTZ_CALENDARS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_CALENDARS
    (
        SCHED_NAME    VARCHAR(120)  NOT NULL,
        CALENDAR_NAME VARCHAR(200)  NOT NULL,
        CALENDAR      VARBINARY(MAX) NOT NULL,
        CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY CLUSTERED (SCHED_NAME, CALENDAR_NAME)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_CRON_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_CRON_TRIGGERS
    (
        SCHED_NAME      VARCHAR(120) NOT NULL,
        TRIGGER_NAME    VARCHAR(150) NOT NULL,
        TRIGGER_GROUP   VARCHAR(150) NOT NULL,
        CRON_EXPRESSION VARCHAR(120) NOT NULL,
        TIME_ZONE_ID    VARCHAR(80)  NULL,
        CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_FIRED_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_FIRED_TRIGGERS
    (
        SCHED_NAME        VARCHAR(120) NOT NULL,
        ENTRY_ID          VARCHAR(140) NOT NULL,
        TRIGGER_NAME      VARCHAR(150) NOT NULL,
        TRIGGER_GROUP     VARCHAR(150) NOT NULL,
        INSTANCE_NAME     VARCHAR(200) NOT NULL,
        FIRED_TIME        BIGINT       NOT NULL,
        SCHED_TIME        BIGINT       NOT NULL,
        PRIORITY          INTEGER      NOT NULL,
        STATE             VARCHAR(16)  NOT NULL,
        JOB_NAME          VARCHAR(150) NULL,
        JOB_GROUP         VARCHAR(150) NULL,
        IS_NONCONCURRENT  BIT          NULL,
        REQUESTS_RECOVERY BIT          NULL,
        CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, ENTRY_ID)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_PAUSED_TRIGGER_GRPS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_PAUSED_TRIGGER_GRPS
    (
        SCHED_NAME    VARCHAR(120) NOT NULL,
        TRIGGER_GROUP VARCHAR(150) NOT NULL,
        CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_GROUP)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_SCHEDULER_STATE', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_SCHEDULER_STATE
    (
        SCHED_NAME        VARCHAR(120) NOT NULL,
        INSTANCE_NAME     VARCHAR(200) NOT NULL,
        LAST_CHECKIN_TIME BIGINT       NOT NULL,
        CHECKIN_INTERVAL  BIGINT       NOT NULL,
        CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY CLUSTERED (SCHED_NAME, INSTANCE_NAME)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_LOCKS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_LOCKS
    (
        SCHED_NAME VARCHAR(120) NOT NULL,
        LOCK_NAME  VARCHAR(40)  NOT NULL,
        CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY CLUSTERED (SCHED_NAME, LOCK_NAME)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_JOB_DETAILS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_JOB_DETAILS
    (
        SCHED_NAME        VARCHAR(120)  NOT NULL,
        JOB_NAME          VARCHAR(150)  NOT NULL,
        JOB_GROUP         VARCHAR(150)  NOT NULL,
        DESCRIPTION       VARCHAR(250)  NULL,
        JOB_CLASS_NAME    VARCHAR(250)  NOT NULL,
        IS_DURABLE        BIT           NOT NULL,
        IS_NONCONCURRENT  BIT           NOT NULL,
        IS_UPDATE_DATA    BIT           NOT NULL,
        REQUESTS_RECOVERY BIT           NOT NULL,
        JOB_DATA          VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY CLUSTERED (SCHED_NAME, JOB_NAME, JOB_GROUP)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_SIMPLE_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_SIMPLE_TRIGGERS
    (
        SCHED_NAME      VARCHAR(120) NOT NULL,
        TRIGGER_NAME    VARCHAR(150) NOT NULL,
        TRIGGER_GROUP   VARCHAR(150) NOT NULL,
        REPEAT_COUNT    BIGINT       NOT NULL,
        REPEAT_INTERVAL BIGINT       NOT NULL,
        TIMES_TRIGGERED BIGINT       NOT NULL,
        CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_SIMPROP_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_SIMPROP_TRIGGERS
    (
        SCHED_NAME    VARCHAR(120)   NOT NULL,
        TRIGGER_NAME  VARCHAR(150)   NOT NULL,
        TRIGGER_GROUP VARCHAR(150)   NOT NULL,
        STR_PROP_1    VARCHAR(512)   NULL,
        STR_PROP_2    VARCHAR(512)   NULL,
        STR_PROP_3    VARCHAR(512)   NULL,
        INT_PROP_1    INT            NULL,
        INT_PROP_2    INT            NULL,
        LONG_PROP_1   BIGINT         NULL,
        LONG_PROP_2   BIGINT         NULL,
        DEC_PROP_1    NUMERIC(13, 4) NULL,
        DEC_PROP_2    NUMERIC(13, 4) NULL,
        BOOL_PROP_1   BIT            NULL,
        BOOL_PROP_2   BIT            NULL,
        TIME_ZONE_ID  VARCHAR(80)    NULL,
        CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    );
GO

IF OBJECT_ID(N'dbo.QRTZ_BLOB_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_BLOB_TRIGGERS
    (
        SCHED_NAME    VARCHAR(120)  NOT NULL,
        TRIGGER_NAME  VARCHAR(150)  NOT NULL,
        TRIGGER_GROUP VARCHAR(150)  NOT NULL,
        BLOB_DATA     VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    );
GO

-- The trigger table references the job table; created after both above exist.
IF OBJECT_ID(N'dbo.QRTZ_TRIGGERS', N'U') IS NULL
    CREATE TABLE dbo.QRTZ_TRIGGERS
    (
        SCHED_NAME     VARCHAR(120)  NOT NULL,
        TRIGGER_NAME   VARCHAR(150)  NOT NULL,
        TRIGGER_GROUP  VARCHAR(150)  NOT NULL,
        JOB_NAME       VARCHAR(150)  NOT NULL,
        JOB_GROUP      VARCHAR(150)  NOT NULL,
        DESCRIPTION    VARCHAR(250)  NULL,
        NEXT_FIRE_TIME BIGINT        NULL,
        PREV_FIRE_TIME BIGINT        NULL,
        PRIORITY       INTEGER       NULL,
        TRIGGER_STATE  VARCHAR(16)   NOT NULL,
        TRIGGER_TYPE   VARCHAR(8)    NOT NULL,
        START_TIME     BIGINT        NOT NULL,
        END_TIME       BIGINT        NULL,
        CALENDAR_NAME  VARCHAR(200)  NULL,
        MISFIRE_INSTR  SMALLINT      NULL,
        JOB_DATA       VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
            REFERENCES dbo.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
    );
GO

-- The child trigger-type tables FK back to QRTZ_TRIGGERS; add the FKs once the parent exists.
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS')
    ALTER TABLE dbo.QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS')
    ALTER TABLE dbo.QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS')
    ALTER TABLE dbo.QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS')
    ALTER TABLE dbo.QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE;
GO

-- Helpful secondary indexes Quartz creates on the busy trigger tables (state scans / next-fire scans).
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_QRTZ_T_NEXT_FIRE_TIME' AND object_id = OBJECT_ID(N'dbo.QRTZ_TRIGGERS'))
    CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON dbo.QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_QRTZ_T_STATE' AND object_id = OBJECT_ID(N'dbo.QRTZ_TRIGGERS'))
    CREATE INDEX IDX_QRTZ_T_STATE ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_QRTZ_T_NEXT_FIRE_TIME_AND_STATE' AND object_id = OBJECT_ID(N'dbo.QRTZ_TRIGGERS'))
    CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME_AND_STATE ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_QRTZ_FT_TRIG_INST_NAME' AND object_id = OBJECT_ID(N'dbo.QRTZ_FIRED_TRIGGERS'))
    CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);
GO
